# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  # Home: /
  Archives: /archives/
  YouTube: https://youtube.com/SNH48Live
  SNH48Live.org: https://snh48live.org
  # Tags: /tags
  # Categories: /categories
  # About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: S2 Blue
  toc: true
  search: false
  fancybox: true

copyright:
  enable: false
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

reward:
  enable: false
  qrCode:
    wechat: /image/reward/wechat.png
    alipay: /image/reward/alipay.png

# ===========================================
# Social links Settings
# ===========================================
social:
  email: snh48live@gmail.com
  stack-overflow:
  twitter: https://twitter.com/snh48live
  facebook:
  linkedin:
  google:
  github: https://github.com/snh48live
  weibo:
  zhihu:
  pocket:
  tumblr: https://snh48live.tumblr.com

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Disqus
disqus_shortname:

# ===========================================
# Version
# ===========================================
version: 2.4.x
